// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Universidad.DBModels;

namespace Universidad.Migrations
{
    [DbContext(typeof(PARCIALDBContext))]
    [Migration("20180627021553_precio")]
    partial class precio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Universidad.DBModels.Alumno", b =>
                {
                    b.Property<int>("Idalumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDAlumno");

                    b.Property<string>("Apellido1")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Apellido2")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Idalumno");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("Universidad.DBModels.Materia", b =>
                {
                    b.Property<int>("Idmateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDMateria");

                    b.Property<int?>("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<double>("Precio");

                    b.HasKey("Idmateria");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("Universidad.DBModels.Matricula", b =>
                {
                    b.Property<int>("Idmatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDMatricula");

                    b.Property<int?>("Idalumno")
                        .HasColumnName("IDAlumno");

                    b.Property<int?>("Idmateria")
                        .HasColumnName("IDMateria");

                    b.Property<int?>("Idprofesor")
                        .HasColumnName("IDProfesor");

                    b.Property<double?>("Nota")
                        .IsRequired();

                    b.HasKey("Idmatricula");

                    b.HasIndex("Idalumno");

                    b.HasIndex("Idmateria");

                    b.HasIndex("Idprofesor");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("Universidad.DBModels.Profesor", b =>
                {
                    b.Property<int>("Idprofesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDProfesor");

                    b.Property<string>("Apellido1")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Apellido2")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Idprofesor");

                    b.ToTable("Profesor");
                });

            modelBuilder.Entity("Universidad.DBModels.Matricula", b =>
                {
                    b.HasOne("Universidad.DBModels.Alumno", "IdalumnoNavigation")
                        .WithMany("Matricula")
                        .HasForeignKey("Idalumno")
                        .HasConstraintName("fk_matricula_alumno");

                    b.HasOne("Universidad.DBModels.Materia", "IdmateriaNavigation")
                        .WithMany("Matricula")
                        .HasForeignKey("Idmateria")
                        .HasConstraintName("fk_matricula_materia");

                    b.HasOne("Universidad.DBModels.Profesor", "IdprofesorNavigation")
                        .WithMany("Matricula")
                        .HasForeignKey("Idprofesor")
                        .HasConstraintName("fk_matricula_profesor");
                });
#pragma warning restore 612, 618
        }
    }
}
